#ifdef CRT_BEGIN
#if 0

asm(".globl __wasm_null\n\t"
    ".text\n\t"
    "createsig FvE\n\t"
    ".pushsection .space.import_.null\n\t"
    ".reloc .,R_WASM32_CODE_POINTER,0f\n\t"
    ".byte 0\n\t"
    ".popsection\n\t"
    ".pushsection .wasm.import_.null\n\t"
    "0:      lstring \"sys\"\n\t"
    "lstring \"null\"\n\t"
    ".byte 0\n\t"
    "rleb128 __sigchar_FvE\n\t"
    ".popsection\n\t"
    ".pushsection .space.function_index.import_.null,\"\"\n\t"
    ".type __wasm_null, @function\n\t"
    ".size __wasm_null, 1\n\t"
    "__wasm_null:\n\t"
    ".reloc .,R_WASM32_INDEX,1f\n\t"
    ".byte 0\n\t"
    ".popsection\n\t"
    ".pushsection .space.element.import_.null\n\t"
    ".reloc .,R_WASM32_CODE_POINTER,0f\n\t"
    "1:      .byte 0\n\t"
    ".popsection\n\t"
    ".pushsection .wasm.element.import_.null\n\t"
    "0:      rleb128_32 __wasm_null\n\t"
    ".popsection\n\t"
    ".if 0\n\t"
    ".pushsection .space.name.function.import_.null\n\t"
    ".byte 0\n\t"
    ".popsection\n\t"
    ".pushsection .wasm.name.function.import_.null\n\t"
    "lstring null\n\t"
    ".byte 0\n\t"
    ".popsection\n\t"
    ".endif\n\t");

asm("\t.pushsection .space.global\n"
    "\t.byte 0\n"
    "\t.popsection\n"
    "\t.pushsection .space.global_index\n"
    "\t.globl __wasm_stack_pointer\n"
    "__wasm_stack_pointer:\n"
    "\t.byte 0\n"
    "\t.popsection\n"
    "\t.pushsection .wasm.global\n"
    "\t.byte 0x7f\n"
    "\t.byte 1\n"
    "\ti32.const 0\n"
    "\tend\n"
    "\t.popsection\n");

asm(".pushsection .space.global_index.import\n\t"
    ".byte 0\n\t"
    ".byte 0\n\t"
    ".byte 0\n\t"
    ".popsection\n\t");

#endif
#endif

#include "../../crtstuff.c"
